"use client";

import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { eventDefaultValues } from "@/constants";
import { createEvent, updateEvent } from "@/lib/actions/event.actions";
import { IEvent } from "@/lib/database/models/event.model";
import { useUploadThing } from "@/lib/uploadthing";
import { eventFormSchema } from "@/lib/validator";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  CalendarPlus,
  FileText,
  Loader2,
  RefreshCcw,
  Sparkles,
} from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import "react-datepicker/dist/react-datepicker.css";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { toast } from "sonner";
import Dropdown from "./Dropdown";
import { FileUploader } from "./FileUploader";
import Image from "next/image";
import { Checkbox } from "../ui/checkbox";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

type EventFormProps = {
  userId: string;
  type: "Create" | "Update";
  event?: IEvent;
  eventId?: string;
};

const EventForm = ({ userId, type, event, eventId }: EventFormProps) => {
  const [files, setFiles] = useState<File[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  const initialValues =
    event && type === "Update"
      ? {
          ...event,
          startDateTime: new Date(event.startDateTime),
          endDateTime: new Date(event.endDateTime),
        }
      : eventDefaultValues;

  const router = useRouter();
  const { startUpload } = useUploadThing("imageUploader");

  const form = useForm<z.infer<typeof eventFormSchema>>({
    resolver: zodResolver(eventFormSchema),
    defaultValues: initialValues,
  });

  async function autoWriteDescription(
    tone: "friendly" | "formal" | "concise" = "friendly"
  ) {
    const title = form.getValues("title");
    if (!title || title.trim().length === 0) {
      toast.error("Please enter an event title first.");
      return;
    }

    try {
      setIsGenerating(true);

      const res = await fetch("/api/openrouter/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, tone }),
      });

      const data = await res.json();

      if (!res.ok) {
        console.error("OpenRouter route error:", data);
        toast.error("AI failed: " + (data?.error || "unknown"));
        return;
      }

      if (data?.description) {
        form.setValue("description", data.description, { shouldDirty: true });
        toast.success("Description generated by AI.");
      } else {
        toast.error("AI returned empty response.");
        console.error("AI response (unexpected):", data);
      }
    } catch (err) {
      console.error("Client AI call failed:", err);
      toast.error("Something went wrong while contacting AI.");
    } finally {
      setIsGenerating(false);
    }
  }

  async function onSubmit(values: z.infer<typeof eventFormSchema>) {
    let uploadedImageUrl = values.imageUrl;

    if (files.length > 0) {
      try {
        const uploadedImages = await startUpload(files);

        if (!uploadedImages) {
          toast.error("Failed to upload image. Please try again.");
          return;
        }

        uploadedImageUrl = uploadedImages[0].url;
      } catch (error) {
        console.error(error);
        toast.error("Something went wrong during image upload.");
        return;
      }
    }

    if (type === "Create") {
      try {
        const newEvent = await createEvent({
          event: { ...values, imageUrl: uploadedImageUrl },
          userId,
          path: "/profile",
        });

        if (newEvent) {
          form.reset();
          toast.success("Event created successfully!");
          router.push(`/events/${newEvent._id}`);
        }
      } catch (error) {
        console.error(error);
        toast.error("Failed to create event. Please try again.");
      }
    } else {
      if (!eventId) {
        toast.error("Invalid event. Unable to update.");
        router.back();
        return;
      }

      try {
        const updatedEvent = await updateEvent({
          userId,
          event: { ...values, imageUrl: uploadedImageUrl, _id: eventId },
          path: `/events/${eventId}`,
        });

        if (updatedEvent) {
          form.reset();
          toast.success("Event updated successfully!");
          router.push(`/events/${updatedEvent._id}`);
        }
      } catch (error) {
        console.error(error);
        toast.error("Failed to update event. Please try again.");
      }
    }
  }

  return (
    <Form {...form}>
      <form
        onSubmit={form.handleSubmit(onSubmit)}
        className="flex flex-col gap-5"
      >
        <div className="grid w-full gap-8 md:grid-cols-2">
          {/* Title */}
          <FormField
            control={form.control}
            name="title"
            render={({ field }) => (
              <FormItem className="w-full space-y-2">
                <label className="text-sm font-medium text-muted-foreground">
                  Event Title
                </label>

                <FormControl>
                  <div className="flex items-center h-[50px] w-full rounded-xl border border-border bg-white dark:bg-neutral-900 px-4 gap-3 transition-all hover:border-primary/50 focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/30">
                    <FileText className="h-5 w-5 text-muted-foreground" />
                    <Input
                      {...field}
                      placeholder="Enter event name"
                      className="w-full bg-transparent border-none outline-none shadow-none focus:ring-0"
                    />
                  </div>
                </FormControl>

                <FormMessage />
              </FormItem>
            )}
          />

          {/* Category */}
          <FormField
            control={form.control}
            name="categoryId"
            render={({ field }) => (
              <FormItem className="w-full space-y-2">
                <label className="text-sm font-medium text-muted-foreground">
                  Category
                </label>
                <FormControl>
                  <Dropdown
                    value={field.value}
                    onChangeHandler={field.onChange}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>

        <div className="grid w-full gap-8 md:grid-cols-2">
          {/* Description + AI */}
          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem className="w-full space-y-2">
                <div className="flex items-center justify-between">
                  <label className="text-sm font-medium text-muted-foreground">
                    Description
                  </label>

                  <div className="flex items-center gap-2">
                    {/* Optional tone quick buttons */}
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => autoWriteDescription("concise")}
                      disabled={isGenerating}
                    >
                      Concise
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => autoWriteDescription("formal")}
                      disabled={isGenerating}
                    >
                      Formal
                    </Button>

                    <Button
                      type="button"
                      onClick={() => autoWriteDescription("friendly")}
                      disabled={isGenerating}
                      className="h-8 px-3 rounded-md flex items-center gap-1"
                    >
                      {isGenerating ? (
                        <>
                          <Loader2 className="w-4 h-4 animate-spin" />
                          Writing...
                        </>
                      ) : (
                        <>
                          <Sparkles className="w-4 h-4" />
                          Write with AI
                        </>
                      )}
                    </Button>
                  </div>
                </div>

                <FormControl>
                  <Textarea
                    {...field}
                    placeholder="Write a short description about the event..."
                    className="min-h-[260px] rounded-xl border border-border bg-white dark:bg-neutral-900 p-4 text-sm transition-all resize-none hover:border-primary/50 focus:ring-2 focus:ring-primary"
                  />
                </FormControl>

                <FormMessage />
              </FormItem>
            )}
          />
          {/* Event Image */}
          <FormField
            control={form.control}
            name="imageUrl"
            render={({ field }) => (
              <FormItem className="w-full space-y-2">
                <label className="text-sm font-medium text-muted-foreground">
                  Event Image
                </label>

                <FormControl>
                  <div
                    className="min-h-[260px] rounded-xl border border-border bg-white dark:bg-neutral-900
                       p-3 transition-all flex-center
                       hover:border-primary/50 focus-within:ring-2 focus-within:ring-primary"
                  >
                    <FileUploader
                      onFieldChange={field.onChange}
                      imageUrl={field.value}
                      setFiles={setFiles}
                    />
                  </div>
                </FormControl>

                <FormMessage />
              </FormItem>
            )}
          />
        </div>

        <div className="w-full">
          <FormField
            control={form.control}
            name="location"
            render={({ field }) => (
              <FormItem className="w-full space-y-2">
                <label className="text-sm font-medium text-muted-foreground">
                  Location
                </label>

                <FormControl>
                  <div className="flex items-center h-[50px] w-full rounded-xl border border-border bg-white dark:bg-neutral-900 px-4 transition-all hover:border-primary/50 focus-within:ring-2 focus-within:ring-primary">
                    <Image
                      src="/assets/icons/location-grey.svg"
                      alt="location"
                      width={18}
                      height={18}
                      className="opacity-70"
                    />

                    <Input
                      {...field}
                      placeholder="Event location or Online"
                      className="w-full bg-transparent border-none outline-none shadow-none focus:ring-0"
                    />
                  </div>
                </FormControl>

                <FormMessage />
              </FormItem>
            )}
          />
        </div>
        <div className="grid w-full gap-6 md:grid-cols-2">
          {/* Start Date */}
          <FormField
            control={form.control}
            name="startDateTime"
            render={({ field }) => (
              <FormItem className="w-full space-y-2">
                <label className="text-sm font-medium text-muted-foreground">
                  Start Date & Time
                </label>

                <FormControl>
                  <div className="flex items-center h-[50px] w-full rounded-xl border border-border bg-white dark:bg-neutral-900 px-4 transition-all hover:border-primary/50 focus-within:ring-2 focus-within:ring-primary">
                    <Image
                      src="/assets/icons/calendar.svg"
                      alt="calendar"
                      width={18}
                      height={18}
                      className="opacity-70"
                    />

                    <DatePicker
                      selected={field.value}
                      onChange={(date: Date) => field.onChange(date)}
                      showTimeSelect
                      timeInputLabel="Time:"
                      dateFormat="MM/dd/yyyy h:mm aa"
                      wrapperClassName="datePicker w-full"
                      className="w-full bg-transparent border-none outline-none focus:outline-none"
                    />
                  </div>
                </FormControl>

                <FormMessage />
              </FormItem>
            )}
          />

          {/* End Date */}
          <FormField
            control={form.control}
            name="endDateTime"
            render={({ field }) => (
              <FormItem className="w-full space-y-2">
                <label className="text-sm font-medium text-muted-foreground">
                  End Date & Time
                </label>

                <FormControl>
                  <div className="flex items-center h-[50px] w-full rounded-xl border border-border bg-white dark:bg-neutral-900 px-4 transition-all hover:border-primary/50 focus-within:ring-2 focus-within:ring-primary">
                    <Image
                      src="/assets/icons/calendar.svg"
                      alt="calendar"
                      width={18}
                      height={18}
                      className="opacity-70"
                    />

                    <DatePicker
                      selected={field.value}
                      onChange={(date: Date) => field.onChange(date)}
                      showTimeSelect
                      timeInputLabel="Time:"
                      dateFormat="MM/dd/yyyy h:mm aa"
                      wrapperClassName="datePicker w-full"
                      className="w-full bg-transparent border-none outline-none focus:outline-none"
                    />
                  </div>
                </FormControl>

                <FormMessage />
              </FormItem>
            )}
          />
        </div>
        <div className="flex flex-col gap-5 md:flex-row">
          {/* PRICE FIELD */}
          <FormField
            control={form.control}
            name="price"
            render={({ field }) => (
              <FormItem className="w-full space-y-2">
                <label className="text-sm font-medium text-muted-foreground">
                  Ticket Price
                </label>
                <FormControl>
                  <div className="flex items-center h-[50px] w-full rounded-xl bg-white dark:bg-neutral-900 border border-border px-4 focus-within:ring-2 focus-within:ring-primary transition">
                    <Image
                      src="/assets/icons/dollar.svg"
                      alt="dollar"
                      width={18}
                      height={18}
                      className="opacity-60"
                    />
                    <Input
                      type="number"
                      placeholder="Enter price"
                      {...field}
                      className="ml-3 w-full border-none bg-transparent p-0 outline-none focus-visible:ring-0"
                    />
                  </div>
                </FormControl>
                <FormMessage />

                <FormField
                  control={form.control}
                  name="isFree"
                  render={({ field }) => (
                    <div className="flex items-center gap-2 pt-1">
                      <Checkbox
                        id="isFree"
                        checked={field.value}
                        onCheckedChange={field.onChange}
                      />
                      <label
                        htmlFor="isFree"
                        className="text-sm text-muted-foreground cursor-pointer"
                      >
                        Free ticket
                      </label>
                    </div>
                  )}
                />
              </FormItem>
            )}
          />

          {/* URL FIELD */}
          <FormField
            control={form.control}
            name="url"
            render={({ field }) => (
              <FormItem className="w-full space-y-2">
                <label className="text-sm font-medium text-muted-foreground">
                  Event URL (optional)
                </label>
                <FormControl>
                  <div className="flex items-center h-[50px] w-full rounded-xl bg-white dark:bg-neutral-900 border border-border px-4 focus-within:ring-2 focus-within:ring-primary transition">
                    <Image
                      src="/assets/icons/link.svg"
                      alt="link"
                      width={18}
                      height={18}
                      className="opacity-60"
                    />
                    <Input
                      placeholder="Enter link"
                      {...field}
                      className="ml-3 w-full border-none bg-transparent p-0 outline-none focus-visible:ring-0"
                    />
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>

        <Button
          type="submit"
          size="lg"
          disabled={form.formState.isSubmitting}
          className="col-span-2 w-full rounded-xl font-medium bg-primary text-primary-foreground hover:bg-primary/90 transition-all disabled:opacity-60 disabled:cursor-not-allowed shadow-sm hover:shadow focus-visible:ring-2 focus-visible:ring-primary/50 flex items-center justify-center gap-2"
        >
          {form.formState.isSubmitting ? (
            <>
              <Loader2 className="h-5 w-5 animate-spin" />
              Submitting…
            </>
          ) : (
            <>
              {type === "Create" ? (
                <CalendarPlus className="h-5 w-5" />
              ) : (
                <RefreshCcw className="h-5 w-5" />
              )}
              {type} Event
            </>
          )}
        </Button>
      </form>
    </Form>
  );
};

export default EventForm;
